### ISSUE TITLE
方便透露项目会用 AI 来做什么吗？

### ISSUE THREAD

**Issue by Ferry-200** [Super-Badmen-Viper/NSMusicS#41]
如题。我觉得应该是基于播放次数和音乐标签（艺术家、专辑等）来推断用户喜好。还有别的方向吗？

**Comment by Super-Badmen-Viper** [comment]
> 如题。我觉得应该是基于播放次数和音乐标签（艺术家、专辑等）来推断用户喜好。还有别的方向吗？

如图所示：
![image](https://github.com/Super-Badmen-Viper/NSMusicS/assets/83256054/45216ffa-d04a-421b-add0-84301b4104db)
除了AI推荐系统(go+知识图谱)外，还有
 - 用于K歌模式的AI修音和AI评分
 - 基于声纹技术的听歌识曲
 - 基于nlp的乐谱生成
 - 歌词制作(使用nlp等做为制作辅助，用户只需完善歌词细节)
 - 音乐社区(用户可选择上传使用数据至NSMusicS官网，用模型来分析用户群像，从而影响NSMusicS的后续开发调整，根据用户需求不断调整NSMusicS)
以上都在NSMusicS规划之中，前后端与云服务都需要开发到位，任重而道远，不过我会一直开源做下去
