### ISSUE TITLE
自定义左边菜单栏

### ISSUE THREAD

**Issue by emyia2001** [Super-Badmen-Viper/NSMusicS#51]
可以添加一个自定义左边菜单栏选择的功能吗？

**Comment by Super-Badmen-Viper** [comment]
> 可以添加一个自定义左边菜单栏选择的功能吗？

是不是控制左边菜单栏中的菜单项是否显示的功能，比如设置只显示[菜单，主页，专辑，乐曲，歌手]，其它的菜单项则隐藏是吧。
这个功能已经实现，但是并未开放。既然有必要的话，我会在下个版本更新开放这个功能。
你到时候检查NSMusicS客户端右上角那一排最左边的按钮是否有红点，有红点就是有更新的版本，点击它进入更新面板，点击下载链接就能自动浏览器下载安装包(或者手动进入Github发布界面自主选择安装版本)

**Comment by emyia2001** [comment]
是的，非常感谢

**Comment by Super-Badmen-Viper** [comment]
> 是的，非常感谢

自定义左侧菜单栏功能已添加，在“菜单-通用“中即可设置，你看看有没有什么问题或者需要改进的

**Comment by Super-Badmen-Viper** [comment]
需求已解决，此issues已关闭
