### ISSUE TITLE
专辑封面BUG

### ISSUE THREAD

**Issue by emyia2001** [Super-Badmen-Viper/NSMusicS#52]
乐曲封面正常显示，但是在专辑页面封面丢失
![image](https://github.com/user-attachments/assets/dacd7ba1-3950-4ebd-b8a3-fa087c9f7a8e)

**Comment by Super-Badmen-Viper** [comment]
> 乐曲封面正常显示，但是在专辑页面封面丢失 ![image](https://private-user-images.githubusercontent.com/75084293/364784957-dacd7ba1-3950-4ebd-b8a3-fa087c9f7a8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDY1MDMsIm5iZiI6MTcyNTU0NjIwMywicGF0aCI6Ii83NTA4NDI5My8zNjQ3ODQ5NTctZGFjZDdiYTEtMzk1MC00ZWJkLWI4YTMtZmEwODdjOWY3YThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE0MjMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMzQ0ZDQxMjJlNjk1NWNkNTgwMzhlZDRhMzUwYmYwM2EzYWU4ZDI3MjM0Y2IxOTgwZWJlMmY1YTkxNjQyYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JC7sfv5OUa3fn7Fj5BBbFQHgFBzfO8naGJ6B-yIjvjc)

你使用的是本地模式，还是服务器模式？一般情况服务器模式很难出现BUG，如果是本地模式，那就是tag类库逻辑的问题，我会在下一个版本修复tag类库逻辑并升级tag类库版本(8.*升级到10.*版本)
请等待NSMusicS版本更新后(右上角那一排最左边的按钮，有更新会冒红点，点击即可打开更新界面，下载最新安装包)
你可以再次重新导入一次本地模式(先清除一次本地模式数据，最新版本地导入有清除数据按钮)

**Comment by emyia2001** [comment]
> > 乐曲封面正常显示，但是在专辑页面封面丢失 ![image](https://private-user-images.githubusercontent.com/75084293/364784957-dacd7ba1-3950-4ebd-b8a3-fa087c9f7a8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDY1MDMsIm5iZiI6MTcyNTU0NjIwMywicGF0aCI6Ii83NTA4NDI5My8zNjQ3ODQ5NTctZGFjZDdiYTEtMzk1MC00ZWJkLWI4YTMtZmEwODdjOWY3YThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE0MjMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMzQ0ZDQxMjJlNjk1NWNkNTgwMzhlZDRhMzUwYmYwM2EzYWU4ZDI3MjM0Y2IxOTgwZWJlMmY1YTkxNjQyYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JC7sfv5OUa3fn7Fj5BBbFQHgFBzfO8naGJ6B-yIjvjc)
> 
> 你使用的是本地模式，还是服务器模式？一般情况服务器模式很难出现BUG，如果是本地模式，那就是tag类库逻辑的问题，我会在下一个版本修复tag类库逻辑并升级tag类库版本(8.*升级到10.*版本)
> 请等待NSMusicS版本更新后(右上角那一排最左边的按钮，有更新会冒红点，点击即可打开更新界面，下载最新安装包)
> 你可以再次重新导入一次本地模式(先清除一次本地模式数据，最新版本地导入有清除数据按钮)

用的服务器模式，明天我重新添加服务器试试

**Comment by Super-Badmen-Viper** [comment]
既然你使用的是服务器模式，如果可以的话，我想知道你的navidrome版本号是多少(可能老版本的接口不兼容)，你的navidrome是你自己个人搭建的吗(有的第三方使用navidrome搭建的公共服，存在访问速率限制)

**Comment by emyia2001** [comment]
> 至于你使用的是服务器模式，如果可以的话，我想知道你的navidrome版本号是多少（可能老版本的接口不兼容），你的navidrome是你自己个人搭建的吗（有第三方使用navidrome搭建吗的公共服务，存在访问速率限制）

使用0.2.6版本后问题已解决，navidrome是我自建的
![image](https://github.com/user-attachments/assets/85de48b2-f026-4d29-91e7-36ac366bd896)
也有可能是我昨天刮削可能有问题导致的这个问题

**Comment by Super-Badmen-Viper** [comment]
> > 至于你使用的是服务器模式，如果可以的话，我想知道你的navidrome版本号是多少（可能老版本的接口不兼容），你的navidrome是你自己个人搭建的吗（有第三方使用navidrome搭建吗的公共服务，存在访问速率限制）
> 
> 使用0.2.6版本后问题已解决，navidrome是我自建的 ![image](https://private-user-images.githubusercontent.com/75084293/365045154-85de48b2-f026-4d29-91e7-36ac366bd896.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTA2MzQsIm5iZiI6MTcyNTYxMDMzNCwicGF0aCI6Ii83NTA4NDI5My8zNjUwNDUxNTQtODVkZTQ4YjItZjAyNi00ZDI5LTkxZTctMzZhYzM2NmJkODk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA4MTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzOTczNWZiYjE3NjY3Yzg2NGZkMzRkOGFkZmE5ZTRkZjFmN2FkZThlZTZhZDNlMmY4ODBjZTRiZjAyMzljNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EWYb-6yI3tfTIjCxkgkY_HRwwZsyiUtN2okuAxTj3Po) 也有可能是我昨天刮削可能有问题导致的这个问题

已收到，如果仍有其它问题或者需求，都可以在issues中提出
