### ISSUE TITLE
v7.1版本 window平台成功安装但是打开立刻闪退了，大佬，能解决一下吗？

### ISSUE THREAD

**Issue by city0928** [Super-Badmen-Viper/NSMusicS#57]
安装路径没有中文。
管理员方式打开也立即闪退。

**Comment by Super-Badmen-Viper** [comment]
> 安装路径没有中文。 管理员方式打开也立即闪退。

一般情况来说，绝大部分用户的PC测试都不会有类似闪退的问题，Electron的兼容性很强，NSMusicS本身就是默认管理员权限，所以几乎只能是系统问题。
你得确保并排查是否存在以下问题：
 - 1.你的电脑中的文件系统是否存在文件加密与访问权限限制的问题(如果有，请检查是否是全盘全局加密)。
 - 2.你所使用的windows系统是否是正版，是否是完整更新过未阉割的版本(原则上系统版本不能低于win10以下)
 - 3.你的电脑硬件配置，比如内存含量是否太低(原则上内存不能低于4G)
 - 4.检查文件系统是否存在C盘，并且检查C:\Users\Public\Documents\NSMusicS文件夹是否拥有正常的公用权限
如若以上措施没有解决问题，请更新升级windows驱动与系统版本并再次运行检测是否还会闪退

**Comment by Super-Badmen-Viper** [comment]
此问题已经在https://github.com/Super-Badmen-Viper/NSMusicS/issues/77 中得到解决，
请尝试重新下载https://github.com/Super-Badmen-Viper/NSMusicS/releases/tag/NSMusicS-Win-v1.0.8
安装最新版后再次检查是否能够成功运行
请在3天内给予答复，3天后我将关闭此issues
如有其它问题，建议，需求，请重新开启issues进行说明

**Comment by Super-Badmen-Viper** [comment]
此issues已解决，现在关闭它
如有其它问题，建议，需求，请重新开启issues进行说明
