### ISSUE TITLE
提供Electron任务栏应用Tray托盘，关闭窗体可保持后台服务

### ISSUE THREAD

**Issue by ray154856235** [Super-Badmen-Viper/NSMusicS#65]
版本  1.0.0
![image](https://github.com/user-attachments/assets/c97071a9-2834-40ff-b666-437bb3bab3b9)

**Comment by Super-Badmen-Viper** [comment]
这个问题已经解决，但是要在下个版本更新。
我将尽快修复当前所有的错误，并更新下一版本。

[BUG及修复代码如下](https://github.com/Super-Badmen-Viper/NSMusicS/commit/fee1f2aa042ad976fb4614a045bb6c5cc1e89aee#diff-3c4362dcdec5fa863d70305ed6f246d031ab4b2a8f1b2cfa4d5fa2faac361f9a): https://github.com/Super-Badmen-Viper/NSMusicS/commit/fee1f2aa042ad976fb4614a045bb6c5cc1e89aee#diff-3c4362dcdec5fa863d70305ed6f246d031ab4b2a8f1b2cfa4d5fa2faac361f9a
为了解决随机播放的问题，我将在下一版本推出播放列表可设置加载指定数目的歌曲，并可按照排序来指定【顺序/循环/随机/播放(根据id，年份，歌手等等排序项加载指定数目的歌曲，添加至播放列表)】

BUG原因是因为navidrome api不支持临时虚拟播放列表，所以随机数的最大获取数不能以navidrome乐库所有歌曲曲目为标准，应该以当前播放列表获取数为标准。
如果要以navidrome乐库所有歌曲曲目为标准，假设曲库有5000首歌曲，随机数到了4000，那么就得播放列表按排序顺序从0开始加载到4000，考虑到网络速度，与部分navidrome服务器的访问速率限制，以及navidrome不支持临时虚拟播放列表，NSMusicS随机播放应以当前播放列表容量为准

**Comment by ray154856235** [comment]
还有缺少个最小化到任务栏右下方

**Comment by Super-Badmen-Viper** [comment]
> 还有缺少个最小化到任务栏右下方

好的，会在1.10版本追加这个功能，再迭代两个版本就行。
到时候顺便会开放跨平台版本。

**Comment by Super-Badmen-Viper** [comment]
此问题已在1.0.2版本中修复：https://github.com/Super-Badmen-Viper/NSMusicS/releases/tag/NSMusicS-Win-v1.0.2
更新设置：服务器即时访问模式初始化加载问题 + 最小化到任务栏右下方（增加了右下角的任务栏托盘）
请在3天内给予我回复，我届时将关闭此issues，感谢你对NSMusicS的贡献

**Comment by ray154856235** [comment]
托盘有了 但是没办法只在托盘后台服务啊,
![image](https://github.com/user-attachments/assets/c1c9b57e-2cd3-4d33-9e6d-8ce3cd7eac09)

**Comment by Super-Badmen-Viper** [comment]
> 托盘有了 但是没办法只在托盘后台服务啊,
> ![image](https://github.com/user-attachments/assets/c1c9b57e-2cd3-4d33-9e6d-8ce3cd7eac09)
> 

我明白了，你想要的是酷狗那种
右上角最小化 ：在任务栏中保留
右上角关闭：在任务栏中删除图标，但是保留后台在托盘，可在托盘中重新打开应用
托盘的退出按钮，才是真正的退出NSMusicS
是不是以上这些？

**Comment by ray154856235** [comment]
对  pc端几乎所有的音乐播放器都是这样的

**Comment by Super-Badmen-Viper** [comment]
> 对 pc端几乎所有的音乐播放器都是这样的

OK，下个版本就会更新这个托盘后台服务功能

**Comment by Super-Badmen-Viper** [comment]
> 对 pc端几乎所有的音乐播放器都是这样的

![7207c0a646c1bb3298c6c92cc5b23def](https://github.com/user-attachments/assets/168d5c86-0143-4119-a3b1-252735a7d152)
托盘后台服务已经开发完成，关闭窗体后后台服务完全正常，下一个版本开放就会更新这个功能
当然，令我意想不到的是，关闭窗体保持后台服务时，Electron的内存下降了1~1.5倍以上，占用内存为之前的30%到45%之间，而且功能完全不受其影响
只能说非常感谢你的建议了[doge]，这对内存优化有巨大的提升

**Comment by Super-Badmen-Viper** [comment]
> 对 pc端几乎所有的音乐播放器都是这样的

经过各类综合调试，关闭窗口开启托盘后台服务
渲染层内存占用能降低20%以上
数据层内存占用能够降低50%以上
综合能够降低30%~40%以上的内存占用
很好的解决了NSMusicS自带的内存自动清理所带来的问题(清理内存时会出现持续一瞬间的杂音，闪屏)

**Comment by Super-Badmen-Viper** [comment]
此issues中需求已在1.0.6版本中更新完成
现在关闭此issues
如有bug，需求，建议等等，请重新提交issues补充
