### ISSUE TITLE
[改进] 能否实现跟随系统切换浅色深色主题？

### ISSUE THREAD

**Issue by youlan2333** [Super-Badmen-Viper/NSMusicS#67]

**Comment by Super-Badmen-Viper** [comment]
完全可以，下个版本就更新设置：【是否跟随系统切换浅色深色主题】
到时候接收更新就OK

**Comment by Super-Badmen-Viper** [comment]
此问题已在1.0.2版本中修复：https://github.com/Super-Badmen-Viper/NSMusicS/releases/tag/NSMusicS-Win-v1.0.2
更新设置：【是否跟随系统切换浅色深色主题】，只有在NSMusicS启动初始化时，才会检测系统主题颜色才响应切换至系统主题，为了性能考虑，并不会即时检测系统的主题变化
请在3天内给予我回复，我届时将关闭此issues，感谢你对NSMusicS的贡献

**Comment by Super-Badmen-Viper** [comment]
更新设置：【是否跟随系统切换浅色深色主题】，已修复完成
如有其它bug，需求，建议，请重新创建新issues进行说明
