### ISSUE TITLE
无法读取我本地音乐内嵌的封面

### ISSUE THREAD

**Issue by Qhzy1411** [Super-Badmen-Viper/NSMusicS#68]
[Pictures.zip](https://github.com/user-attachments/files/17253238/Pictures.zip)
压缩包内含：音乐文件，musictag截图，播放器无法正常读取封面截图
![PixPin_2024-10-04_12-11-20](https://github.com/user-attachments/assets/b57477d7-fbde-4bc6-bebf-4830f5f3749f)
![PixPin_2024-10-04_12-10-23](https://github.com/user-attachments/assets/24eeb71d-39b5-409f-b761-80c0de97eee9)

**Comment by Super-Badmen-Viper** [comment]
下一个版本更新才会支持：增加本地模式导入歌曲文件封面
目前版本不会读取内嵌的封面，需要音乐文件所在文件夹内存在同名的png封面才能读取
可使用musictag导出音乐文件的封面即可
![image](https://github.com/user-attachments/assets/b828f84f-4b9f-4d96-a875-55575fae7087)

**Comment by Super-Badmen-Viper** [comment]
此问题已在1.0.2版本中修复：https://github.com/Super-Badmen-Viper/NSMusicS/releases/tag/NSMusicS-Win-v1.0.2
当导入音乐文件夹同名文件夹内没有同名的音乐封面时，则自动从文件内嵌封面导出保存至同名文件夹
请在3天内给予我回复，我届时将关闭此issues，感谢你对NSMusicS的贡献

**Comment by Super-Badmen-Viper** [comment]
读取内嵌封面需求已完成，此issues已关闭
下一版本将可设置封面导入的路径：可选择导入源文件夹，或者自定义的文件夹内。
 - 推荐导入源文件夹，符合国际音乐类软件的通用规范 
 
如有其它bug，需求，建议，请重新创建新issues进行说明
