### ISSUE TITLE
添加navidrome服务器时提示“无效的服务器”

### ISSUE THREAD

**Issue by houzhe12345** [Super-Badmen-Viper/NSMusicS#69]
第一次使用，添加自己的navidrome服务器时提示“无效的服务器”。添加navidrome官方demo站点时，也是如此。

**Comment by Super-Badmen-Viper** [comment]
> 第一次使用，添加自己的navidrome服务器时提示“无效的服务器”。添加navidrome官方demo站点时，也是如此。

我觉得应该是你多加了一个"/"，端口号后面不能带"/"，就算你使用官方navidrome旗下的客户端feishin，你端口号也是不能加"/"的，示例：http://localhost:4533

**Comment by houzhe12345** [comment]
我的格式是这样的 http://192.168.10.40:4533

**Comment by Super-Badmen-Viper** [comment]
这个就可能是Navidrome版本的问题了，因为Navidrome不会对版本更新做API接口兼容，
所以有的版本登录验证是通过不了的，这也是我为什么要自己开发流媒体云服务的原因。
你需要先保证你的navidrome服务正常启动，可以在浏览器中进行访问。
如果Navidrome启动正常，麻烦你给我看看你的Navidrome版本号是多少，我好针对版本号进行优化改进

**Comment by Super-Badmen-Viper** [comment]
![image](https://github.com/user-attachments/assets/b7b34bbd-5987-45b7-8e32-7ddb94668e50)
<img width="728" alt="image" src="https://github.com/user-attachments/assets/f089cb4c-e38f-4606-862a-a0da00bd426c">
你需要按照以上流程，来验证登录，如果还是不行，请向我提交你的Navidrome版本号
不过我觉得你还是先在浏览器测试你的navidrome是否能够成功访问登录使用

**Comment by houzhe12345** [comment]
navidrome是能正常使用的，版本号Version:	0.49.3-SNAPSHOT (2cd43581)
然后我发现 我更换一台电脑后 是可以正常添加的

**Comment by Super-Badmen-Viper** [comment]
> navidrome是能正常使用的，版本号Version: 0.49.3-SNAPSHOT (2cd43581) 然后我发现 我更换一台电脑后 是可以正常添加的

那应该是你之前那台电脑的端口访问有问题(也许是没开放端口，也许是端口被占用，也许是外部访问网络有问题)
既然你的问题已经解决，那么我将关闭此issues
如有其它问题，需求，建议，请重新在NSMusicS创建新issues
