### ISSUE TITLE
navidrome拉不到歌，按说明提交一下错误提示

### ISSUE THREAD

**Issue by qingkeee** [Super-Badmen-Viper/NSMusicS#70]
index-C6Kgn0jn.js:3203 undefined
C:/Program%20Files/NSMusicS/resources/app.asar/assets/index-C6Kgn0jn.png:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
index-C6Kgn0jn.js:3202 C:\Users\Public\Documents\NSMusicS\navidrome.db
index-C6Kgn0jn.js:3202 C:\Users\Public\Documents\NSMusicS\nsmusics.db
index-C6Kgn0jn.js:2836 E:\0_Music
index-C6Kgn0jn.js:2696 zhHans
8index-C6Kgn0jn.js:2879 save config succuessful
index-C6Kgn0jn.js:2879 this_audio_file_path：http://localhost:4533/rest/stream?u=mozhi&t=3c048c2b6d7a0ff52074d1150e1874d5&s=8YuHYv&v=1.12.0&c=nsmusics&f=json&id=d0dd9037ff50feac7e771938b8cdb26a
index-C6Kgn0jn.js:2879 this_audio_file_medium_image_urlhttp://localhost:4533/rest/getCoverArt?u=mozhi&t=3c048c2b6d7a0ff52074d1150e1874d5&s=8YuHYv&v=1.12.0&c=nsmusics&f=json&id=d0dd9037ff50feac7e771938b8cdb26a
index-C6Kgn0jn.js:2879 this_audio_song_id：d0dd9037ff50feac7e771938b8cdb26a
index-C6Kgn0jn.js:2879 this_audio_song_rating：NaN
index-C6Kgn0jn.js:2879 this_audio_album_name：红蔷薇白玫瑰
index-C6Kgn0jn.js:2879 this_audio_album_id：34ef398dca70c1a15c98d5f62bb6f9e1
2index-C6Kgn0jn.js:2879 save config succuessful
C:/Program%20Files/NSMusicS/resources/app.asar/undefined/api/song?_end=100&_order=ASC&_sort=id&_start=0&title=&starred=&album_id=&artist_id=&year=:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
C:/Program%20Files/NSMusicS/resources/app.asar/undefined/rest/scrobble?u=mozhi&t=&s=&v=1.12.0&c=nsmusics&f=json&id=d0dd9037ff50feac7e771938b8cdb26a&time=&submission=:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
C:/Program%20Files/NSMusicS/resources/app.asar/undefined/rest/scrobble?u=mozhi&t=&s=&v=1.12.0&c=nsmusics&f=json&id=34ef398dca70c1a15c98d5f62bb6f9e1&time=&submission=:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
index-C6Kgn0jn.js:17 TypeError: Cannot read properties of undefined (reading 'playlists')
    at Set_Navidrome_ALL_Data_To_LocalSqlite.Set_Read_Navidrome_Api_PlayListInfo_Add_LocalSqlite (index-C6Kgn0jn.js:2833:1133)
    at async Proxy.Get_UserData_Synchronize_ToLocal_of_ND (index-C6Kgn0jn.js:2836:15936)
    at async Proxy.reset_data (index-C6Kgn0jn.js:2761:1155)
    at async Proxy.load_app_config (index-C6Kgn0jn.js:2836:13484)
    at async index-C6Kgn0jn.js:3202:20339
logError @ index-C6Kgn0jn.js:17
C:/Program%20Files/NSMusicS/resources/app.asar/undefined/rest/getPlaylists?u=mozhi&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
index-C6Kgn0jn.js:2879 save config succuessful
index-C6Kgn0jn.js:3202 View_Album_List_ALL
index-C6Kgn0jn.js:2879 save config succuessful
undefined/rest/getStarred2?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getScanStatus?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getArtists?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getPlaylists?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/api/album?_end=100&_order=ASC&_sort=id&_start=0&name=&starred=&artist_id=:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'starred2')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_starred (index-C6Kgn0jn.js:2820:1020)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scanStatus')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_media_file (index-C6Kgn0jn.js:2820:554)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'artists')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_artist_album (index-C6Kgn0jn.js:2820:705)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'playlists')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_playlist (index-C6Kgn0jn.js:2820:1426)
localhost:4533/rest/getCoverArt?u=mozhi&t=3c048c2b6d7a0ff52074d1150e1874d5&s=8YuHYv&v=1.12.0&c=nsmusics&f=json&id=d0dd9037ff50feac7e771938b8cdb26a:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
index-C6Kgn0jn.js:2879 save config succuessful
index-C6Kgn0jn.js:3202 View_Song_List_ALL
index-C6Kgn0jn.js:2879 save config succuessful
undefined/rest/getScanStatus?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getStarred2?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getPlaylists?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getArtists?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/api/song?_end=100&_order=ASC&_sort=id&_start=0&title=&starred=&album_id=&artist_id=&year=:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scanStatus')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_media_file (index-C6Kgn0jn.js:2820:554)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'starred2')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_starred (index-C6Kgn0jn.js:2820:1020)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'playlists')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_playlist (index-C6Kgn0jn.js:2820:1426)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'artists')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_artist_album (index-C6Kgn0jn.js:2820:705)
index-C6Kgn0jn.js:17 TypeError: Cannot read properties of undefined (reading 'playlists')
    at Set_Navidrome_ALL_Data_To_LocalSqlite.Set_Read_Navidrome_Api_PlayListInfo_Add_LocalSqlite (index-C6Kgn0jn.js:2833:1133)
    at async Proxy.Get_UserData_Synchronize_ToLocal_of_ND (index-C6Kgn0jn.js:2836:15936)
    at async index-C6Kgn0jn.js:2820:4130
logError @ index-C6Kgn0jn.js:17
undefined/rest/getPlaylists?u=mozhi&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
index-C6Kgn0jn.js:2879 save config succuessful
index-C6Kgn0jn.js:3202 View_Artist_List_ALL
index-C6Kgn0jn.js:2879 save config succuessful
undefined/rest/getScanStatus?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getArtists?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getStarred2?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getPlaylists?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/api/artist?_end=100&_order=ASC&_sort=id&_start=0&name=&starred=:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scanStatus')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_media_file (index-C6Kgn0jn.js:2820:554)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'artists')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_artist_album (index-C6Kgn0jn.js:2820:705)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'starred2')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_starred (index-C6Kgn0jn.js:2820:1020)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'playlists')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_playlist (index-C6Kgn0jn.js:2820:1426)
localhost:4533/rest/getCoverArt?u=mozhi&t=3c048c2b6d7a0ff52074d1150e1874d5&s=8YuHYv&v=1.12.0&c=nsmusics&f=json&id=d0dd9037ff50feac7e771938b8cdb26a:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
localhost:4533/rest/getCoverArt?u=mozhi&t=3c048c2b6d7a0ff52074d1150e1874d5&s=8YuHYv&v=1.12.png:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
View_Song_List_ALL-CbMO11qr.js:104 Uncaught TypeError: Cannot set properties of null (setting 'src')
    at M.T.onerror (View_Song_List_ALL-CbMO11qr.js:104:4026)
index-C6Kgn0jn.js:3202 View_Song_List_ALL
2index-C6Kgn0jn.js:2879 save config succuessful
undefined/rest/getScanStatus?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getArtists?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getPlaylists?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getStarred2?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/api/song?_end=100&_order=ASC&_sort=id&_start=0&title=&starred=&album_id=&artist_id=&year=:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scanStatus')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_media_file (index-C6Kgn0jn.js:2820:554)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'artists')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_artist_album (index-C6Kgn0jn.js:2820:705)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'playlists')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_playlist (index-C6Kgn0jn.js:2820:1426)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'starred2')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_starred (index-C6Kgn0jn.js:2820:1020)
index-C6Kgn0jn.js:17 TypeError: Cannot read properties of undefined (reading 'playlists')
    at Set_Navidrome_ALL_Data_To_LocalSqlite.Set_Read_Navidrome_Api_PlayListInfo_Add_LocalSqlite (index-C6Kgn0jn.js:2833:1133)
    at async Proxy.Get_UserData_Synchronize_ToLocal_of_ND (index-C6Kgn0jn.js:2836:15936)
    at async index-C6Kgn0jn.js:2820:4130
logError @ index-C6Kgn0jn.js:17
undefined/rest/getPlaylists?u=mozhi&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
localhost:4533/rest/getCoverArt?u=mozhi&t=3c048c2b6d7a0ff52074d1150e1874d5&s=8YuHYv&v=1.12.0&c=nsmusics&f=json&id=d0dd9037ff50feac7e771938b8cdb26a:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
index-C6Kgn0jn.js:2879 save config succuessful
index-C6Kgn0jn.js:3202 View_Menu_AppSetting
index-C6Kgn0jn.js:2879 save config succuessful
undefined/rest/getScanStatus?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getArtists?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getPlaylists?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined/rest/getStarred2?u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scanStatus')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_media_file (index-C6Kgn0jn.js:2820:554)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'artists')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_artist_album (index-C6Kgn0jn.js:2820:705)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'playlists')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_playlist (index-C6Kgn0jn.js:2820:1426)
index-C6Kgn0jn.js:2820 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'starred2')
    at Get_Navidrome_Temp_Data_To_LocalSqlite.get_count_of_starred (index-C6Kgn0jn.js:2820:1020)
localhost:4533/rest/getCoverArt?u=mozhi&t=3c048c2b6d7a0ff52074d1150e1874d5&s=8YuHYv&v=1.12.png:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by Super-Badmen-Viper** [comment]
这个就可能是Navidrome版本的问题了，因为Navidrome不会对版本更新做API接口兼容，
所以有的版本登录验证是通过不了的，这也是我为什么要自己开发流媒体云服务的原因。
你需要先保证你的navidrome服务正常启动，可以在浏览器中进行访问。
如果Navidrome启动正常，麻烦你给我看看你的Navidrome版本号是多少，我好针对版本号进行优化改进

**Comment by Super-Badmen-Viper** [comment]
哥们，你好像用的是我的空白测试navidrome，那玩意是不管用的，给你做参考用的
你得自己配置一个navidrome服务器才行
你看看这些访问日志：u=mozhi&t=3c048c2b6d7a0ff52074d1150e1874d5&s=8YuHYv&v=1.12.0&c=nsmusics&f=json
这可不是你的navidrome服务器，你需要自己配置一个才行

**Comment by Super-Badmen-Viper** [comment]
你好像用的是我的空白测试navidrome，那玩意是不管用的
你得自己配置一个navidrome服务器并登录刷新才行
你看这访问日志：
u=mozhi&t=3c048c2b6d7a0ff52074d1150e1874d5&s=8YuHYv&v=1.12.0&c=nsmusics&f=json

还有这个访问日志：
undefined/rest/getArtists？u=undefined&t=540a01260a851cd721f4b0009048babb&s=UBhBnn&v=1.12.0&c=nsmusics&f=json
这说明你没有登录Navidrome，你的接口信息都没有对上

还有可能是Navidrome版本的问题了，因为Navidrome不会对版本更新做API接口兼容，
所以有的版本登录验证是通过不了的，这也是我为什么要自己开发流媒体云服务的原因。
你需要先保证你的navidrome服务正常启动，可以在浏览器中进行访问。
如果Navidrome启动正常，麻烦你给我看看你的Navidrome版本号是多少，我好针对版本号进行优化改进

**Comment by Super-Badmen-Viper** [comment]
![image](https://github.com/user-attachments/assets/b7b34bbd-5987-45b7-8e32-7ddb94668e50)
<img width="728" alt="image" src="https://github.com/user-attachments/assets/f089cb4c-e38f-4606-862a-a0da00bd426c">
你需要按照以上流程，来验证登录，如果还是不行，请向我提交你的Navidrome版本号

**Comment by qingkeee** [comment]
可以了，确实之前设置问题，谢谢

**Comment by Super-Badmen-Viper** [comment]
问题已解决，issues已关闭
如果其它问题，需求，建议，请重新开启issues进行提交
