### ISSUE TITLE
win11最新1.05客户端播放音乐 暂停后 再次继续就没有声音了

### ISSUE THREAD

**Issue by Ccnavi** [Super-Badmen-Viper/NSMusicS#73]
环境：
操作系统：win11 专业版 22h2 22621.1702
媒体服务器：navidrome 0.53.3
客户端：NSMusicS 1.0.5

问题描述：
1.点开歌曲详情页 出现歌词页面暂停后 等待两秒再点击继续 音乐不会继续播放 无声 但是 进度条 还在走秒，并且歌词还会回到开头。
![image](https://github.com/user-attachments/assets/43f632b0-7de6-4329-96fa-a0d830fd472e)
目前播放切换到淡进淡出 暂时能够避免卡住无声，读秒问题。
希望作者看下这个能不能修复或者更改一下 会不会是mpv问题 导致的

**Comment by Super-Badmen-Viper** [comment]
OK，现在就解决，待会发布1.0.6版本，我这边没多少测试的确很难测出BUG

**Comment by Ccnavi** [comment]
好的 等你出新的 我再试试

**Comment by Super-Badmen-Viper** [comment]
> 好的 等你出新的 我再试试

问题已排查成功，正在打包1.0.6
MPV并不支持播放过程中淡入淡出，现在NSMusicS的MPV淡入淡出效果是我手写实现的通过控制临时音量线性变化，而实现的淡入淡出效果，今天刚适配完毕
因为没有完整的测试用例，靠我自己的确很难能够100%覆盖的测试，感谢你对NSMusicS的贡献

**Comment by Ccnavi** [comment]
嗯 服务端 今年有计划上线吗  以及移动端 安卓和iOS 整体UI风格可以的

**Comment by Ccnavi** [comment]
> 嗯 服务端 今年有计划上线吗 以及移动端 安卓和iOS 整体UI风格可以的

杜比音效调用的win的吗

**Comment by Super-Badmen-Viper** [comment]
> 嗯 服务端 今年有计划上线吗 以及移动端 安卓和iOS 整体UI风格可以的

服务器端目前在刚起步的阶段，预计在2025年1月23号之前推出公测版，在明年3月前应该可以推出正式版
移动端估计是要明年这个时候了

**Comment by Super-Badmen-Viper** [comment]
> > 嗯 服务端 今年有计划上线吗 以及移动端 安卓和iOS 整体UI风格可以的
> 
> 杜比音效调用的win的吗

杜比音效其实是调用howler.js自带的设置，它通过指定音频格式的容器来进行杜比音质的解码

不过mpv同样可以通过调整各参数，达到极致的音质设置

我使用howler.js，更多的是考虑收听较好的音质的同时，实现其丰富的音效，毕竟howler.js基于web audio api，并且提供了自定义音效插件的接口

**Comment by Ccnavi** [comment]
> > 嗯 服务端 今年有计划上线吗 以及移动端 安卓和iOS 整体UI风格可以的
> 
> 服务器端目前在刚起步的阶段，预计在2025年1月23号之前推出公测版，在明年3月前应该可以推出正式版 移动端估计是要明年这个时候了

好的 客户端可以出一个每日推荐这个栏目 这样用户使用起来更方便并且粘性会高

**Comment by Super-Badmen-Viper** [comment]
> > > 嗯 服务端 今年有计划上线吗 以及移动端 安卓和iOS 整体UI风格可以的
> > 
> > 
> > 服务器端目前在刚起步的阶段，预计在2025年1月23号之前推出公测版，在明年3月前应该可以推出正式版 移动端估计是要明年这个时候了
> 
> 好的 客户端可以出一个每日推荐这个栏目 这样用户使用起来更方便并且粘性会高

客户端在“主页”页面中，会随机从曲库中挑选专辑，这其实算是简单的推荐
复杂的歌曲推荐功能，我会在NSMusicS-GO的服务器端中实现，不仅会使用基于GO的开源推荐系统(内置一系列推荐算法)，还会使用{ 知识图谱-图数据库} 来进行用户数据的分析来推荐

**Comment by Ccnavi** [comment]
> > > > 嗯 服务端 今年有计划上线吗 以及移动端 安卓和iOS 整体UI风格可以的
> > > 
> > > 
> > > 服务器端目前在刚起步的阶段，预计在2025年1月23号之前推出公测版，在明年3月前应该可以推出正式版 移动端估计是要明年这个时候了
> > 
> > 
> > 好的 客户端可以出一个每日推荐这个栏目 这样用户使用起来更方便并且粘性会高
> 
> 客户端在“主页”页面中，会随机从曲库中挑选专辑，这其实算是简单的推荐 复杂的歌曲推荐功能，我会在NSMusicS-GO的服务器端中实现，不仅会使用基于GO的开源推荐系统(内置一系列推荐算法)，还会使用{ 知识图谱-图数据库} 来进行用户数据的分析来推荐

OK 新客户端在上传了嘛 或者直接给我链接下载也行

**Comment by Super-Badmen-Viper** [comment]
> > > > > 嗯 服务端 今年有计划上线吗 以及移动端 安卓和iOS 整体UI风格可以的
> > > > 
> > > > 
> > > > 服务器端目前在刚起步的阶段，预计在2025年1月23号之前推出公测版，在明年3月前应该可以推出正式版 移动端估计是要明年这个时候了
> > > 
> > > 
> > > 好的 客户端可以出一个每日推荐这个栏目 这样用户使用起来更方便并且粘性会高
> > 
> > 
> > 客户端在“主页”页面中，会随机从曲库中挑选专辑，这其实算是简单的推荐 复杂的歌曲推荐功能，我会在NSMusicS-GO的服务器端中实现，不仅会使用基于GO的开源推荐系统(内置一系列推荐算法)，还会使用{ 知识图谱-图数据库} 来进行用户数据的分析来推荐
> 
> OK 新客户端在上传了嘛 或者直接给我链接下载也行

今晚的校园网，的确有点慢，稍等一会，马上就上传好了

**Comment by Ccnavi** [comment]
> > > > > > 嗯 服务端 今年有计划上线吗 以及移动端 安卓和iOS 整体UI风格可以的
> > > > > 
> > > > > 
> > > > > 服务器端目前在刚起步的阶段，预计在2025年1月23号之前推出公测版，在明年3月前应该可以推出正式版 移动端估计是要明年这个时候了
> > > > 
> > > > 
> > > > 好的 客户端可以出一个每日推荐这个栏目 这样用户使用起来更方便并且粘性会高
> > > 
> > > 
> > > 客户端在“主页”页面中，会随机从曲库中挑选专辑，这其实算是简单的推荐 复杂的歌曲推荐功能，我会在NSMusicS-GO的服务器端中实现，不仅会使用基于GO的开源推荐系统(内置一系列推荐算法)，还会使用{ 知识图谱-图数据库} 来进行用户数据的分析来推荐
> > 
> > 
> > OK 新客户端在上传了嘛 或者直接给我链接下载也行
> 
> 今晚的校园网，的确有点慢，稍等一会，马上就上传好了

好

**Comment by Super-Badmen-Viper** [comment]
上传完成，1.0.6版本，mpv问题已修复

**Comment by Super-Badmen-Viper** [comment]
等一下，有个属性填错了，马上，不好意思[doge]，影响到淡入淡出效果了

**Comment by Ccnavi** [comment]
> 等一下，有个属性填错了，马上，不好意思[doge]，影响到淡入淡出效果了

1

**Comment by Ccnavi** [comment]
> 等一下，有个属性填错了，马上，不好意思[doge]，影响到淡入淡出效果了

ok了嘛

**Comment by Super-Badmen-Viper** [comment]
> > 等一下，有个属性填错了，马上，不好意思[doge]，影响到淡入淡出效果了
> 
> 1

已发布：https://github.com/Super-Badmen-Viper/NSMusicS/releases/download/NSMusicS-Win-v1.0.6/NSMusicS.Setup.1.0.6.exe

**Comment by Ccnavi** [comment]
> > > 等一下，有个属性填错了，马上，不好意思[doge]，影响到淡入淡出效果了
> > 
> > 
> > 1
> 
> 已发布：https://github.com/Super-Badmen-Viper/NSMusicS/releases/download/NSMusicS-Win-v1.0.6/NSMusicS.Setup.1.0.6.exe

好

**Comment by Ccnavi** [comment]
> > > 等一下，有个属性填错了，马上，不好意思[doge]，影响到淡入淡出效果了
> > 
> > 
> > 1
> 
> 已发布：https://github.com/Super-Badmen-Viper/NSMusicS/releases/download/NSMusicS-Win-v1.0.6/NSMusicS.Setup.1.0.6.exe

 可以了 问题解决了

**Comment by Super-Badmen-Viper** [comment]
OK，如果有其他BUG，需求，建议等等，请提交issues至Github NSMusicS，感谢你对NSMusicS的贡献
