### ISSUE TITLE
Add and select output devices | 添加选择输出设备

### ISSUE THREAD

**Issue by FNTDemo** [Super-Badmen-Viper/NSMusicS#74]
可以添加选择输出设备吗？

**Comment by Super-Badmen-Viper** [comment]
OK，下次版本将更新：选择输出设备

**Comment by Super-Badmen-Viper** [comment]
此issues已在1.1.3版本中修复：https://github.com/Super-Badmen-Viper/NSMusicS/releases/tag/NSMusicS-v1.1.3
如有其它疑问，请重新开启issues进行发布
