### ISSUE TITLE
左侧状态栏

### ISSUE THREAD

**Issue by songchunyang0213** [Super-Badmen-Viper/NSMusicS#78]
![PixPin_2024-10-25_13-27-10](https://github.com/user-attachments/assets/b4cc3f02-2beb-4dd0-8ab0-f766da28b5ff)
单击流派以下的功能时会出现如图这样全部视为选中状态

**Comment by Super-Badmen-Viper** [comment]
那是因为这些功能都没有开放，使用的是同一路由空页面，自然就会全部选中
页面说明已经写了：Not open || 未开放

**Comment by Super-Badmen-Viper** [comment]
这些未开放的页面路由，都是为了给NSMusicS-GO服务器端预留的位置
当然你也可以通过菜单 - 通用 - 侧边栏设定，来隐藏左侧路由的功能按键
