### ISSUE TITLE
其他系统的支持计划

### ISSUE THREAD

**Issue by baogutang** [Super-Badmen-Viper/NSMusicS#81]
请问什么时候会支持macOS啊大佬？有个大概的时间么？一直在等~

**Comment by Super-Badmen-Viper** [comment]
> 请问什么时候会支持macOS啊大佬？有个大概的时间么？一直在等~

![截屏2024-11-26 21 37 23](https://github.com/user-attachments/assets/b688ab23-387d-4c03-bae4-5039531418b7)
看看这是啥[doge]
目前对接macos的问题需要解决以下两个问题
1.系统应用托盘跨平台兼容
2.数据库读写位置跨平台兼容
正在做了，解决完就会发布1.1.0版本（win，macos）

**Comment by Super-Badmen-Viper** [comment]
感觉月底之前应该可以的，毕竟问题不多

**Comment by Super-Badmen-Viper** [comment]
不过这次发布macos不会先兼容本地模式（只兼容本地模式），因为我被macos的文件系统权限弄得头疼，主要是第一次用macos系统，没习惯，之前只用过win。
macos版本要完全兼容本地模式，还需要我慢慢摸索macos系统的脾气

**Comment by Super-Badmen-Viper** [comment]
如果你是本地音乐用户，但是我这不会先兼容本地模式，到时候你可以在macos装个navidrome，如果安装麻烦的话，用docker装也行。
我会尽快完全兼容好macos

**Comment by baogutang** [comment]
> 如果你是本地音乐用户，但是我这不会先兼容本地模式，到时候你可以在macos装个navidrome，如果安装麻烦的话，用docker装也行。 我会尽快完全兼容好macos

就是navidrome哈哈哈哈哈

**Comment by Super-Badmen-Viper** [comment]
> > 如果你是本地音乐用户，但是我这不会先兼容本地模式，到时候你可以在macos装个navidrome，如果安装麻烦的话，用docker装也行。 我会尽快完全兼容好macos
> 
> 就是navidrome哈哈哈哈哈

MacOS版本已发布，你要不要试试[doge]
https://github.com/Super-Badmen-Viper/NSMusicS/releases/tag/NSMusicS-v1.1.0

**Comment by Super-Badmen-Viper** [comment]
MacOSX M系列芯片版本系统已兼容，剩余Intel系统版本系统仍未支持，后续将增加对Intel版本的MacOSX的支持
由于Issues已重复，将关闭此Issues
此Issues与此链接Issues合并：https://github.com/Super-Badmen-Viper/NSMusicS/issues/83
