### ISSUE TITLE
Need to fix the error pop-up caused by thread connection calls during local/server mode switching | 需要修复本地/服务器模式切换期间，线程连接调用导致的错误弹出窗口

### ISSUE THREAD

**Issue by wangxiongkun** [Super-Badmen-Viper/NSMusicS#85]
初次安装，多次切换音源会报错
![image](https://github.com/user-attachments/assets/7c419064-0f3f-49fe-8aae-7fbb374043d7)

**Comment by Super-Badmen-Viper** [comment]
此issues已在1.1.3版本中修复：https://github.com/Super-Badmen-Viper/NSMusicS/releases/tag/NSMusicS-v1.1.3
如有其它疑问，请重新开启issues进行发布
