### ISSUE TITLE
小小建议~ 希望可以“界面设置”隐藏

### ISSUE THREAD

**Issue by i-iooi-i** [Super-Badmen-Viper/NSMusicS#89]
![image](https://github.com/user-attachments/assets/df1e2dd4-b21c-4a6a-81be-3db162be34d3)

大佬，在B站看到了NSMusicS，很喜欢。
首次安装来用，有些直观的感受，提一下建议哈。

比如上面这个“界面设置” 是否可以放到下面三个点的菜单里隐藏起来了，它看上去使用频率并不高，在一定程度上影响了界面的简洁，在这个界面会情不自禁盯着这里的字看。 😂

**Comment by Super-Badmen-Viper** [comment]
完全可以，下个版本会修复这个
后续会重构调整播放界面的样式，这个到时候会优化好的
这方面设计还是得向Apple Music看齐啊

**Comment by i-iooi-i** [comment]
> 完全可以，下个版本会修复这个 后续会重构调整播放界面的样式，这个到时候会优化好的 这方面设计还是得向Apple Music看齐啊

辛苦大佬哇🌹，会保持关注的，一直在桌面端找不到很酷又好用的播放器播放NAS里的歌曲，这下有救啦。

**Comment by Super-Badmen-Viper** [comment]
此issues已在1.1.4版本中解决：https://github.com/Super-Badmen-Viper/NSMusicS/releases/tag/NSMusicS-v1.1.4
我将在3天内关闭此issues
如有其它需求或问题，请重新开启一个新的issues
