### ISSUE TITLE
[BUG]关于播放界面的小问题

### ISSUE THREAD

**Issue by lllll081926i** [Super-Badmen-Viper/NSMusicS#93]
![image](https://github.com/user-attachments/assets/600a917c-da36-4862-8e58-1e05f0da6aef)
鼠标只有到最下面才能点到按钮，版本win 1.1.3

**Comment by Super-Badmen-Viper** [comment]
已收到，下一版本会修复
底部播放栏的专辑悬浮按钮也能开启 | 关闭播放界面

**Comment by Super-Badmen-Viper** [comment]
此issues已在1.1.4版本中解决：https://github.com/Super-Badmen-Viper/NSMusicS/releases/tag/NSMusicS-v1.1.4
我将在3天内关闭此issues
如有其它需求或问题，请重新开启一个新的issues
